services:
  - type: web
    name: jumin-masker
    env: python
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: starter
